In [76]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
torch.manual_seed(2)

In [77]:
X = torch.Tensor([[0,0],[0,1], [1,0], [1,1]])
Y = torch.Tensor([0,1,1,0]).view(-1,1)

In [78]:
class XOR(nn.Module):
    def __init__(self, input_dim = 2, output_dim=1):
        super(XOR, self).__init__()
        self.lin1 = nn.Linear(input_dim, 2)
        self.lin2 = nn.Linear(2, output_dim)
    
    def forward(self, x):
        x = self.lin1(x)
        x = F.relu(x)
        x = self.lin2(x)
        return x

In [79]:
model = XOR()

In [80]:
def weights_init(model):
    for m in model.modules():
        if isinstance(m, nn.Linear):
            # initialize the weight tensor, here we use a normal distribution
            m.weight.data.normal_(0, 1)

weights_init(model)

In [81]:
loss_func = nn.MSELoss()

In [82]:
optimizer = optim.Adam(model.parameters(), lr=0.0001)

In [83]:
epochs = 10001
steps = X.size(0)
for i in range(epochs):
    for j in range(steps):
        data_point = np.random.randint(X.size(0))
        x_var = Variable(X[data_point], requires_grad=False)
        y_var = Variable(Y[data_point], requires_grad=False)
        
        optimizer.zero_grad()
        y_hat = model(x_var)
        loss = loss_func.forward(y_hat, y_var)
        loss.backward()
        optimizer.step()
        
    if i % 500 == 0:
        print(y_hat)
        print("Epoch: {0}, Loss: {1}, ".format(i, loss.data.numpy()))

tensor([-0.4615], grad_fn=<AddBackward0>)
Epoch: 0, Loss: 0.21298818290233612, 
tensor([-1.1787], grad_fn=<AddBackward0>)
Epoch: 500, Loss: 1.3893505334854126, 
tensor([-0.6011], grad_fn=<AddBackward0>)
Epoch: 1000, Loss: 0.3612685799598694, 
tensor([-0.6452], grad_fn=<AddBackward0>)
Epoch: 1500, Loss: 2.7065937519073486, 
tensor([0.1205], grad_fn=<AddBackward0>)
Epoch: 2000, Loss: 0.014528144150972366, 
tensor([0.6545], grad_fn=<AddBackward0>)
Epoch: 2500, Loss: 0.11934919655323029, 
tensor([0.4939], grad_fn=<AddBackward0>)
Epoch: 3000, Loss: 0.24391748011112213, 
tensor([0.2651], grad_fn=<AddBackward0>)
Epoch: 3500, Loss: 0.5401094555854797, 
tensor([0.3522], grad_fn=<AddBackward0>)
Epoch: 4000, Loss: 0.12407005578279495, 
tensor([0.4432], grad_fn=<AddBackward0>)
Epoch: 4500, Loss: 0.31007206439971924, 
tensor([0.2239], grad_fn=<AddBackward0>)
Epoch: 5000, Loss: 0.05014360323548317, 
tensor([0.8054], grad_fn=<AddBackward0>)
Epoch: 5500, Loss: 0.037881266325712204, 
tensor([0.8317], g

In [84]:
model_params = list(model.parameters())

In [85]:
model_params

[Parameter containing:
 tensor([[-0.7597, -0.4776],
         [ 0.7230,  0.7230]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4776, -0.7117], requires_grad=True),
 Parameter containing:
 tensor([[-2.1265, -1.3831]], requires_grad=True),
 Parameter containing:
 tensor([1.0156], requires_grad=True)]

In [86]:
model(X)

tensor([[0.0000e+00],
        [9.9999e-01],
        [9.9999e-01],
        [4.4107e-06]], grad_fn=<AddmmBackward>)

In [87]:
loss_func.forward(model(X), Y).data.numpy()

array(2.1241675e-11, dtype=float32)

In [102]:
F.relu(model.lin1(torch.Tensor([1,1])))

tensor([0.0000, 0.7343], grad_fn=<ReluBackward0>)

In [103]:
model.lin1(torch.Tensor([1,1]))

tensor([-0.7598,  0.7343], grad_fn=<AddBackward0>)

In [105]:
model_params[0]

Parameter containing:
tensor([[-0.7597, -0.4776],
        [ 0.7230,  0.7230]], requires_grad=True)

In [110]:
torch.matmul(torch.Tensor([1,1]), model_params[0].transpose(0, 1))+torch.Tensor([ 0.4776, -0.7117])

tensor([-0.7598,  0.7343], grad_fn=<AddBackward0>)

In [112]:
torch.matmul(torch.Tensor([1,1]), model_params[0].transpose(0, 1))

tensor([-1.2374,  1.4460], grad_fn=<SqueezeBackward3>)

In [116]:
torch.matmul(torch.Tensor([1,1]), model_params[0].transpose(0, 1))

tensor([-1.2374,  1.4460], grad_fn=<SqueezeBackward3>)