In [28]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
torch.manual_seed(2)

In [29]:
X = torch.Tensor([[0,0],[0,1], [1,0], [1,1]])
Y = torch.Tensor([0,1,1,0]).view(-1,1)

In [30]:
class XOR(nn.Module):
    def __init__(self, input_dim = 2, output_dim=1):
        super(XOR, self).__init__()
        self.lin1 = nn.Linear(input_dim, 2)
        self.lin2 = nn.Linear(2, output_dim)
    
    def forward(self, x):
        x = self.lin1(x)
        x = F.relu(x)
        x = self.lin2(x)
        return x

In [31]:
model = XOR()

In [32]:
def weights_init(model):
    for m in model.modules():
        if isinstance(m, nn.Linear):
            # initialize the weight tensor, here we use a normal distribution
            m.weight.data.normal_(0, 1)

weights_init(model)

In [33]:
loss_func = nn.MSELoss()

In [34]:
optimizer = optim.Adam(model.parameters(), lr=0.0001)

In [35]:
epochs = 501
steps = X.size(0)
for i in range(epochs):
    for j in range(steps):
        data_point = np.random.randint(X.size(0))
        x_var = Variable(X[data_point], requires_grad=False)
        y_var = Variable(Y[data_point], requires_grad=False)
        
        optimizer.zero_grad()
        y_hat = model(x_var)
        loss = loss_func.forward(y_hat, y_var)
        loss.backward()
        optimizer.step()
        
    if i % 500 == 0:
        print("Epoch: {0}, Loss: {1}, ".format(i, loss.data.numpy()))

Epoch: 0, Loss: 3.9081850051879883, 
Epoch: 500, Loss: 0.48008671402931213, 


In [36]:
model_params = list(model.parameters())

In [37]:
model_params

[Parameter containing:
 tensor([[-0.7597,  0.1095],
         [-0.2778,  1.3317]], requires_grad=True),
 Parameter containing:
 tensor([0.2041, 0.0415], requires_grad=True),
 Parameter containing:
 tensor([[-1.1438, -1.3773]], requires_grad=True),
 Parameter containing:
 tensor([0.3072], requires_grad=True)]